variables:
  IMAGE_TAG: v0  # must be kept in sync with lb-docker-run
stages:
  - build
  - test
  - tag

# ==== Build ====
centos7-build:
  stage: build
  tags:
    - docker-image-build
  script: "echo" # unused but this line is required by GitLab CI
  variables:
    FROM: gitlab-registry.cern.ch/lhcb-docker/os-base/centos7-devel:latest
    TO: ${CI_REGISTRY_IMAGE}/centos7-build:${IMAGE_TAG}.${CI_PIPELINE_IID}
    DOCKER_FILE: Dockerfile
    BUILD_ARG: IMAGE_NAME=centos7-build
