# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ostap 

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
jobs:
  test_sevice:
   runs-on: ubuntu-latest 
   steps:
     - uses: cvmfs-contrib/github-action-cvmfs@v2
     - name: Build
       run: |
         ls /cvmfs/sft.cern.ch
  test_docker:
     runs-on: ubuntu-latest 
     needs: test_sevice
     steps:
      - uses: cvmfs-contrib/github-action-cvmfs@v2
      - name: Build
        run: |
         ls /cvmfs/sft.cern.ch
      - uses:  docker://gitlab-registry.cern.ch/lhcb-core/lbdocker/centos7-build:latest
        with: 
          args: -v /cvmfs:/cvmfs:shared --security-opt seccomp=unconfined -u:0 
      - name: Build2
        run: |
          cd ..
          ls
          cd ..
          ls
