# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ostap 

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
jobs:
  test_docker:
    container: gitlab-registry.cern.ch/lhcb-core/lbdocker/centos7-build:latest
    volumes:
        - /cvmfs:/cvmfs:shared
    options: --security-opt seccomp=unconfined
    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - name: Build
      run: |
        ls -al
        
